AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'thigapim'
ENVIRONMENT_TAG: 'prd'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'craigspaterson'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
